### ISSUE TITLE
Detecting builder does not work with all built-in directives

### ISSUE THREAD

**Issue by webard** [LastDragon-ru/lara-asp#68]
Hi,

builder type detection for custom directives works perfect (#85), but current way of detecting builder based on directive class names is not flexible.  In future, when lighthouse introduce some new directives, we will need to specify them in this package each time.

For example, lighthouse has `@count` directive which is used only to count items. It can be used inside type, but as a query too.

When I use schema like:
```
countCoupons(filter: CouponFilter @searchBy): Int @count
```

there is an error:
```
Impossible to determine builder type for `type Query { countCoupons(filter) }`.

  at vendor/lastdragon-ru/lara-asp-graphql/src/Builder/Directives/HandlerDirective.php:220
    216▕                 'document' => $documentAST,
    217▕             ]);
    218▕             $argSource   = $this->getFieldArgumentSource($manipulator, $parentType, $parentField, $argDefinition);
    219▕ 
  ➜ 220▕             throw new BuilderUnknown($argSource);
    221▕         }
    222▕ 
    223▕         // Converted?
    224▕         /** @var Manipulator $manipulator */
```

But we can't change internal lighthouse class so only way now to get it work is clone directive class to project.

**Comment by LastDragon-ru** [comment]
Thanks. I've added `@count`, `@aggregate`, `@withCount` and `@with`, and I hope they were the last missed built-in directives. 

The v3 (and below) used `Eloquent` as default builder type. Unfortunately, it make impossible to find fields where `@searchBy`/`@sortBy` is useless :( (without the direct call of `ArgumentSet::enhanceBuilder()` custom directives don't work at all). The v4 return `null` instead and we will see error until the custom directive implement `BuilderInfoProvider`. Perhaps it is not the best solution, but from my point of view better to see possible errors in the schema asap.

Also, keep in mind that some Lighthouse directives may use different builder specified by arguments, eg Query builder instead of Eloquent. So the code to detect actual builder type is required always. 

> so only way now to get it work is clone directive class to project.

Actually not, you can add custom directive and just use it with `@count`:

```php
<?php declare(strict_types = 1);

namespace App\GraphQL\Directives;

use Illuminate\Database\Eloquent\Builder;
use LastDragon_ru\LaraASP\GraphQL\Builder\BuilderInfo;
use LastDragon_ru\LaraASP\GraphQL\Builder\Contracts\BuilderInfoProvider;
use Nuwave\Lighthouse\Support\Contracts\Directive;

class EloquentDirective implements Directive, BuilderInfoProvider {
    public static function definition(): string {
        return 'directive @eloquent';
    }

    public function getBuilderInfo(): BuilderInfo|string {
        return Builder::class;
    }
}
```

```graphql
countCoupons(filter: CouponFilter @searchBy): Int @count @eloquent
```
